server:
  port: 8003
spring:
  datasource:
    url: jdbc:mysql://47.98.191.109:3306/gmair_chatlog?serverTimezone=CTT&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-active: 200
    max-idle: 20
    min-idle: 10
  #    type: com.mysql.cj.jdbc.MysqlDataSource
  thymeleaf:
    cache: false
  jackson:
    time-zone: GMT+8
  application: # 应用名称
    name: chatlog-analysis

  redis:
    host: 47.98.191.109
    port: 6381
    password: Gmair2022
    timeout: 30000

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: 47.98.191.109:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      bootstrap-servers: 47.98.191.109:9092
      group-id: chatlog-analysis
    bootstrap-servers: 47.98.191.109:9092

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

python:
  env: D:/anaconda/python.exe
  bert-entry: E:/毕设/BERT_Chinese_Classification-master/consumer-kafka.py
  bert:
    config-file: E:/毕设/BERT_Chinese_Classification-master/chinese_L-12_H-768_A-12/bert_config.json
    vocab-file: E:/毕设/BERT_Chinese_Classification-master/chinese_L-12_H-768_A-12/vocab.txt
    checkpoint-dir: E:/毕设/BERT_Chinese_Classification-master/sim_model
    do-train: false
    do_eval: false
    do_predict: true

kafka:
  topics:
    fetch: query_to_analysis
    to-bert: analysis_to_bert
    after-bert: bert_to_analysis

thread-pool:
  core-pool-size: 5
  keep-alive-seconds: 10
  max-pool-size: 10
  queue-capacity: 3
