spring:
  application:
    name: gateway-agent

eureka:
  client:
    healthcheck: true
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/

zuul:
  routes:
    message:
      path: /message/**
      url: http://127.0.0.1:8001/message
    location:
      path: /location/**
      url: http://127.0.0.1:8002/location
    auth-consumer:
      path: /oauth/consumer/token
      url: http://127.0.0.1:8003/oauth/token
    auth-consumer-all:
      path: /auth/consumer/**
      url: http://127.0.0.1:8003/auth
    auth-admin:
      path: /oauth/admin/token
      url: http://127.0.0.1:8004/oauth/token
    auth-consumer-all:
      path: /auth/admin/**
      url: http://127.0.0.1:8004/auth
    auth-installer:
      path: /oauth/installer/**
      url: http://127.0.0.1/oauth
    installation:
      path: /installation/**
      url: http://127.0.0.1:8006/installation


ribbon:
  eureka:
    enabled: true

server:
  port: 8888
