spring:
  application:
    name: gateway-agent

eureka:
  client:
    healthcheck: true
    service-url:
      defaultZone: http://localhost:8000/eureka/

zuul:
  routes:
    management:
      path: /manage/**
      url: http://127.0.0.1:
    message:
      path: /message/**
      url: http://127.0.0.1:8002/message

ribbon:
  eureka:
    enabled: true

server:
  port: 8001
