spring:
  application:
    name: gateway-agent

eureka:
  client:
    healthcheck: true
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/

zuul:
  routes:
    message:
      path: /message/**
      url: http://127.0.0.1:8001/message
    location:
      path: /location/**
      url: http://127.0.0.1:8002/location
    auth:
      path: /auth/**
      url: http://127.0.0.1:8003/auth

ribbon:
  eureka:
    enabled: true

server:
  port: 8888
