CREATE SCHEMA `gmair_data_analysis` DEFAULT CHARACTER SET utf8 ;
-- MySQL Script generated by MySQL Workbench
-- Fri Jan  4 15:43:48 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gmair_data_analysis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gmair_data_analysis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gmair_data_analysis` DEFAULT CHARACTER SET utf8 ;
USE `gmair_data_analysis` ;

-- -----------------------------------------------------
-- Table `gmair_data_analysis`.`indoor_pm25_hourly`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gmair_data_analysis`.`indoor_pm25_hourly` (
  `status_id` VARCHAR(50) NOT NULL,
  `machine_id` VARCHAR(50) NOT NULL,
  `average_pm25` DOUBLE NOT NULL,
  `max_pm25` INT NOT NULL,
  `min_pm25` INT NOT NULL,
  `block_flag` TINYINT(1) NOT NULL DEFAULT '0',
  `create_time` DATETIME NOT NULL,
  PRIMARY KEY (`status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gmair_data_analysis`.`volume_hourly`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gmair_data_analysis`.`volume_hourly` (
  `status_id` VARCHAR(50) NOT NULL,
  `machine_id` VARCHAR(50) NOT NULL,
  `average_volume` DOUBLE NOT NULL,
  `max_volume` INT NOT NULL,
  `min_volume` INT NOT NULL,
  `block_flag` TINYINT(1) NOT NULL DEFAULT '0',
  `create_time` DATETIME NOT NULL,
  PRIMARY KEY (`status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gmair_data_analysis`.`temp_hourly`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gmair_data_analysis`.`temp_hourly` (
  `status_id` VARCHAR(50) NOT NULL,
  `machine_id` VARCHAR(50) NOT NULL,
  `average_temp` DOUBLE NOT NULL,
  `max_temp` INT NOT NULL,
  `min_temp` INT NOT NULL,
  `block_flag` TINYINT(1) NOT NULL DEFAULT '0',
  `create_time` DATETIME NOT NULL,
  PRIMARY KEY (`status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gmair_data_analysis`.`humid_hourly`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gmair_data_analysis`.`humid_hourly` (
  `status_id` VARCHAR(50) NOT NULL,
  `machine_id` VARCHAR(50) NOT NULL,
  `average_humid` DOUBLE NOT NULL,
  `max_humid` INT NOT NULL,
  `min_humid` INT NOT NULL,
  `block_flag` TINYINT(1) NOT NULL DEFAULT '0',
  `create_time` DATETIME NOT NULL,
  PRIMARY KEY (`status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gmair_data_analysis`.`power_hourly`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gmair_data_analysis`.`power_hourly` (
  `status_id` VARCHAR(50) NOT NULL,
  `machine_id` VARCHAR(50) NOT NULL,
  `power_on_minute` INT NOT NULL,
  `power_off_minute` INT NOT NULL,
  `block_flag` TINYINT(1) NOT NULL DEFAULT '0',
  `create_time` DATETIME NOT NULL,
  PRIMARY KEY (`status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gmair_data_analysis`.`mode_hourly`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gmair_data_analysis`.`mode_hourly` (
  `status_id` VARCHAR(50) NOT NULL,
  `machine_id` VARCHAR(50) NOT NULL,
  `manual_minute` INT NOT NULL,
  `cosy_minute` INT NOT NULL,
  `warm_minute` INT NOT NULL,
  `block_flag` TINYINT(1) NOT NULL DEFAULT '0',
  `create_time` DATETIME NOT NULL,
  PRIMARY KEY (`status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gmair_data_analysis`.`heat_hourly`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gmair_data_analysis`.`heat_hourly` (
  `status_id` VARCHAR(50) NOT NULL,
  `machine_id` VARCHAR(50) NOT NULL,
  `heat_on_minute` INT NOT NULL,
  `heat_off_minute` INT NOT NULL,
  `block_flag` TINYINT(1) NOT NULL DEFAULT '0',
  `create_time` DATETIME NOT NULL,
  PRIMARY KEY (`status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gmair_data_analysis`.`co2_hourly`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gmair_data_analysis`.`co2_hourly` (
  `status_id` VARCHAR(50) NOT NULL,
  `machine_id` VARCHAR(50) NOT NULL,
  `average_co2` DOUBLE NOT NULL,
  `max_co2` INT NOT NULL,
  `min_co2` INT NOT NULL,
  `block_flag` TINYINT(1) NOT NULL DEFAULT '0',
  `create_time` DATETIME NOT NULL,
  PRIMARY KEY (`status_id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `gmair_data_analysis`.`user_action`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gmair_data_analysis`.`user_action` (
  `record_id` VARCHAR(50) NOT NULL,
  `machine_id` VARCHAR(50) NOT NULL,
  `user_id` VARCHAR(50) NOT NULL,
  `component` VARCHAR(50) NOT NULL,
  `component_times` INT NOT NULL,
  `block_flag` TINYINT(1) NOT NULL DEFAULT '0',
  `create_time` DATETIME NOT NULL,
  PRIMARY KEY (`record_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
